version = 1

[[analyzers]]
name = "php"

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "kotlin"

  [analyzers.meta]
  runtime_version = "1.8"
  language_version = "1.7"

[[analyzers]]
name = "javascript"